set -g mouse on
setw -g mode-keys vi
set -sg escape-time 0
set -g history-limit 50000
# recommended for Claude Code
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

